version: '3.9'
services:
  postgres:
    image: postgres:15-alpine
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: PIYUSH
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: Bubble
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data:
